### ISSUE TITLE
Example with ReactTransitionGroup

### ISSUE THREAD

**Issue by sashafklein** [rackt/redux-simple-router#136]
We're trying to wrap redux-simple-router navigation (which we've had working for a while) in a ReactTransitionGroup element so that its lifecycle methods can be called on a route change. We've tried a whole bunch of versions, but haven't figured out a way to get it working.

Our current iteration creates a wrapper right under the TransitionGroup (which is a child of Provider) so that lifecycle methods can be defined at a place where both the route state and children are accessible. This wrapper's `render` and `componentWillAppear` methods are definitely called on initial app load (in the browser), but not when navigating (using Redux Simple Router) between pages in the app. That code, more or less, is on [this gist](https://gist.github.com/sashafklein/ef4d9742279010ca7f8f).

Most notably, we tried the cloneElement method from React with a regenerated key (e.g., through history.createKey()) each time, but couldn't get the lifecycle methods to fire on any route changes.

What's the idiomatic way to wrap simple-router components in a ReactTransitionGroup with redux-simple-router?

**Comment by kjbekkelund** [comment]
Hi @sashafklein. I haven't worked with `TransitionGroup` for a while, so can't help much with how it works and if you're using it correctly. The role of redux-simple-router is just to sync the browser URL and the store, and shouldn't impact your code here, so I don't think this repo is the right place to ask this question. (I _think_ your problem is how to get this to work with react-router and redux.) StackOverflow might be a good place to ask.

I'll close this for now, but don't hesitate to let us know if you find any issues related to redux-simple-router when solving this.
