### ISSUE TITLE
Consider routingReducer or routing as name instead of routeReducer

### ISSUE THREAD

**Issue by pedrottimark** [rackt/redux-simple-router#188]
The `routing` store property in redux-simple-router wisely differs in name from the `Route` component in react-router. Thank you for taking the time to consider aligning names as much as possible within this library.

A. To increase parallelism. In the following excerpt from the Tutorial, `routingReducer` seems better than `routeReducer` but keep on reading.

```
import { syncHistory, routeReducer } from 'redux-simple-router'
const reducer = combineReducers(Object.assign({}, reducers, {
  routing: routeReducer
}))
```

The name of a reducer function is often the same as the name of the corresponding state property when you combine reducers, although that is not a requirement, as clearly explained in http://rackt.org/redux/docs/basics/Reducers.html

B. To increase consistency with most Redux examples and lower the level of ES2015 knowledge required (pardon the pun) `routing` seems even better than `routingReducer`

https://github.com/choonkending/react-webpack-node/blob/master/app/reducers/index.js#L4
```
import { routeReducer as routing } from 'redux-simple-router';
```

**Comment by timdorr** [comment]
If we want to get pedantic about it, technically it's `locationReducer`, as it adds a `location` property to your state. If you use it with something like `reduceReducers`, that will be how it comes out.

Because we don't work directly with react-router, it actually has nothing to do with routing. You could technically use this library with just history and no router at all. All we do is handle moving the history, of which the resultant artifact is a location.

But all that said, if we called this project `redux-simple-history`, we might not get the visibility that comes with associating with react-router. As such, I think we should simply keep it for now and for those that want to name it something else can alias the import like you have in your B point.

**Comment by jlongster** [comment]
It's still on my TODO list to rename this to react-router-redux, which is what Ryan wants it to be. I think the idea is that in the future we could integrate better with it. But I agree that it will most likely just work with history.

It's common for reducers to be named the same as the state property so that you can just pass that object into `combineReducers`. For this reducer, you are always going to have to merge it in with your app's reducers so it doesn't matter as much.

We'll keep this in mind though if we do another refactor. I think it's ok for now.

**Comment by pedrottimark** [comment]
Keep up the good work!

1. react-router-redux sounds good: my mind parses it like react-redux, even if analogy is not exact
2. just reducing history location seems like a benefit not a limitation worth emphasizing (history without react-router is the use case that brought me here)

P.S. I have been exploring whether there is a place for me to assist in rackt world with docs for projects which “cross the line” to expand beyond early expert adopters, as Ryan put it.
