### ISSUE TITLE
Invariant violation with Link in list that is removed on click

### ISSUE THREAD

**Issue by crudh** [rackt/redux-simple-router#190]
I have a bunch of links in a list. When I click a Link an action is triggered that clears the list (among other things) and the list is removed. But then I get the following error in the console:

```
Uncaught Error: Invariant Violation: findComponentRoot(..., .0.2.1): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
```

If I remove `syncReduxAndRouter(history, store);` the error message disappears.

This is the same problem as in the closed #54, but I have a runnable example [here](https://github.com/crudh/link-history-bug) that shows the problem.

I have also tested with `@next` but I get the same problem.

**Comment by timdorr** [comment]
Is this still happening with 2.0.2?

**Comment by crudh** [comment]
@timdorr sadly, yes. Example [here](https://github.com/crudh/link-history-bug/tree/next).

**Comment by timdorr** [comment]
Looking at this again, I'm not 100% sure why you're doing this. Namely, why you're using the router navigation to trigger a Redux action. You should be triggering the action directly from the click handler and `routeActions.push()` to go to another URL, if you want to.

What's actually happening is React is getting tripped up in its own internal event loop, causing it to try and resolve the DOM after it's already been resolved by the navigation event. 

Again, this is mainly just an anti-pattern. You should be using your events to drive Redux actions that in turn affect the route, not the other way around.

**Comment by crudh** [comment]
@timdorr But don't I need to trigger a Redux action from the route params if someone loads the app with the param set already? Like in this example linked from the README where  `this.props.params.name` is used to trigger an action: https://github.com/StevenIseki/redux-simple-router-example/blob/master/src/containers/Package.js

Or should I just keep that for such uses cases and handle it differently when the button is clicked inside the app? And then trigger the action and doing the `routeActions.push()`? But then is using `Link` from `react-router` something that should be avoided completely for internal routes?

**Comment by timdorr** [comment]
That's just loading some data when the component mounts. Happens all the time. 

You're running actions when props change on a component that's already connected to the store. The connect maps state from the store to props, so that's a roundabout way of executing an action. You've potentially built an infinite loop, as the connect maps state to props which execute an action that changes state which connect maps to props... etc etc. 

And that kind of circular logic is what is the design pattern problem that I see here. You need to pick something to drive state, which is supposed to be redux and is what redux-simple-router provides. If you start dividing state responsibilities, you'll end up in a world of hurt where you don't always know where actions are coming from or seeing them interact unexpectedly.

**Comment by crudh** [comment]
@timdorr Thank you for the explanation. I have reworked the code now and it feels much more logical and the problem I had is gone.
